<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package AppBundle\Repository
 */
class StoreRepository extends EntityRepository
{
}
