app_api_stock_list:
    path: /api/v1/stores
    controller: AppBundle:Api:stockList
    methods: GET

app_api_stock_show:
    path: /api/v1/stores/{id}
    controller: AppBundle:Api:stockShow
    methods: GET

app_api_product_list:
    path: /api/v1/products
    controller: AppBundle:Api:productList
    methods: GET

app_api_product_show:
    path: /api/v1/products/{id}
    controller: AppBundle:Api:productShow
    methods: GET